import { Sparkles, MapPin, Shuffle, Palette } from 'lucide-react'
import NextOutfitStyleSection from './NextOutfitStyleSection.jsx'

function Tag({ children }) {
  return (
    <span className="inline-block rounded-full bg-ink/5 px-3 py-1 text-xs font-medium text-ink/70 capitalize">
      {children}
    </span>
  )
}

export default function StyleReport({ result }) {
  if (!result) return null
  const { garment_type, pattern, style, style_report, vision_backend, garment_confidence } = result

  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-center gap-2 text-accent mb-1">
          <Sparkles size={16} />
          <span className="text-xs font-semibold uppercase tracking-wide">Outfit Styling Report</span>

        </div>
        <h2 className="font-display text-2xl text-ink leading-snug">{style_report.headline}</h2>
      </div>

      <div className="flex flex-wrap gap-2">
        <Tag>{garment_type}</Tag>
        <Tag>{pattern}</Tag>
        <Tag>{style}</Tag>
        <Tag>{Math.round(garment_confidence * 100)}% confidence</Tag>
      </div>

      <p className="text-ink/75 leading-relaxed">{style_report.analysis}</p>

      <div>
        <h3 className="flex items-center gap-2 font-display text-lg text-ink mb-2">
          <MapPin size={16} className="text-accent" /> Best Occasions
        </h3>
        <ul className="space-y-1.5">
          {style_report.occasions.map((o) => (
            <li key={o} className="text-sm text-ink/70 flex items-start gap-2">
              <span className="mt-1.5 h-1 w-1 rounded-full bg-accent shrink-0" />
              {o}
            </li>
          ))}
        </ul>
      </div>

      <div>
        <h3 className="flex items-center gap-2 font-display text-lg text-ink mb-2">
          <Shuffle size={16} className="text-accent" /> Pairing Suggestions
        </h3>
        <ul className="space-y-1.5">
          {style_report.pairing_suggestions.map((p) => (
            <li key={p} className="text-sm text-ink/70 flex items-start gap-2">
              <span className="mt-1.5 h-1 w-1 rounded-full bg-accent shrink-0" />
              {p}
            </li>
          ))}
        </ul>
      </div>

      <div className="rounded-xl bg-accent/5 border border-accent/15 p-4">
        <h3 className="flex items-center gap-2 text-sm font-semibold text-accent mb-1">
          <Palette size={14} /> Color Tip
        </h3>
        <p className="text-sm text-ink/70">{style_report.color_tip}</p>
      </div>

      {/* Next Outfit Style Variations */}
      <NextOutfitStyleSection nextStyles={style_report.next_outfit_styles} />

      <p className="text-[11px] text-ink/30 pt-2 border-t border-ink/10">
        Analysis engine: {vision_backend} · Report generated by: {style_report.generated_by}
      </p>
    </div>
  )
}

