import { Sparkles, MapPin, Shuffle, Palette } from 'lucide-react'
import NextOutfitStyleSection from './NextOutfitStyleSection.jsx'

function Tag({ children }) {
  return (
    <span className="inline-block rounded-full bg-slate-100 border border-slate-200 px-3 py-1 text-xs font-mono font-semibold text-slate-800 capitalize">
      {children}
    </span>
  )
}

export default function StyleReport({ result, onHoverColor }) {
  if (!result) return null
  const { garment_type, pattern, style, style_report, vision_backend, garment_confidence, dominant_colors } = result

  return (
    <div className="space-y-6">
      {/* Signature Element: Load-Bearing Pinned Palette Strip */}
      {dominant_colors && dominant_colors.length > 0 && (
        <div className="relative group">
          <div className="flex h-2.5 w-full overflow-hidden rounded-full border border-slate-200 bg-slate-100 shadow-inner animate-swatch-reveal">
            {dominant_colors.map((c, idx) => (
              <div
                key={c.hex + idx}
                onMouseEnter={() => onHoverColor?.(c.hex)}
                onMouseLeave={() => onHoverColor?.(null)}
                style={{
                  width: `${Math.max(c.weight * 100, 8)}%`,
                  backgroundColor: c.hex,
                }}
                className="h-full cursor-pointer hover:brightness-110 transition-all duration-150"
                title={`Hover to tint UI with ${c.name} (${c.hex} · ${Math.round(c.weight * 100)}%)`}
              />
            ))}
          </div>
          <div className="flex items-center justify-between text-[10px] text-slate-500 font-mono mt-1 px-0.5">
            <span>EXTRACTED PALETTE STRIP</span>
            <span>HOVER SWATCH TO TINT UI</span>
          </div>
        </div>
      )}

      {/* Header */}
      <div>
        <div className="flex items-center gap-2 text-dynamic-accent mb-1.5">
          <Sparkles size={16} />
          <span className="font-display tracking-wider uppercase text-xs font-bold">
            Outfit Styling Report
          </span>
        </div>
        <h2 className="font-display text-2xl text-slate-900 leading-snug font-bold">
          {style_report.headline}
        </h2>
      </div>

      {/* Attribute Tags */}
      <div className="flex flex-wrap gap-2">
        <Tag>{garment_type}</Tag>
        <Tag>{pattern}</Tag>
        <Tag>{style}</Tag>
        <Tag>{Math.round(garment_confidence * 100)}% confidence</Tag>
      </div>

      {/* Analysis text */}
      <p className="text-slate-700 leading-relaxed text-sm font-normal">{style_report.analysis}</p>

      {/* Best Occasions */}
      <div>
        <h3 className="flex items-center gap-2 font-display tracking-wider uppercase text-xs font-bold text-slate-500 mb-2.5">
          <MapPin size={14} className="text-dynamic-accent" /> Best Occasions
        </h3>
        <ul className="space-y-2">
          {style_report.occasions.map((o) => (
            <li key={o} className="text-sm text-slate-800 flex items-start gap-2.5">
              <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-dynamic-accent shrink-0" />
              {o}
            </li>
          ))}
        </ul>
      </div>

      {/* Pairing Suggestions */}
      <div>
        <h3 className="flex items-center gap-2 font-display tracking-wider uppercase text-xs font-bold text-slate-500 mb-2.5">
          <Shuffle size={14} className="text-dynamic-accent" /> Key Styling & Pairing Rules
        </h3>
        <ul className="space-y-2">
          {style_report.pairing_suggestions.map((p) => (
            <li key={p} className="text-sm text-slate-800 flex items-start gap-2.5">
              <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-dynamic-accent shrink-0" />
              {p}
            </li>
          ))}
        </ul>
      </div>

      {/* Color Tip Box */}
      <div className="rounded-xl bg-slate-50 border-l-4 border-dynamic-accent border-r border-t border-b border-slate-200 p-4">
        <h3 className="flex items-center gap-2 text-xs font-bold text-dynamic-accent uppercase tracking-wider mb-1">
          <Palette size={14} /> Color Harmony Guidance
        </h3>
        <p className="text-sm text-slate-700 leading-relaxed">{style_report.color_tip}</p>
      </div>

      {/* Next Outfit Style Variations */}
      <NextOutfitStyleSection nextStyles={style_report.next_outfit_styles} onHoverColor={onHoverColor} />

      <p className="text-[11px] text-slate-400 pt-3 border-t border-slate-200 font-mono">
        Analysis engine: {vision_backend} · Report generated by: {style_report.generated_by}
      </p>
    </div>
  )
}
